server:
  port: 8082
grpc:
  port: 6567
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: service3
  sleuth:
    grpc:
      enabled: false
    enabled: true
    sampler:
      percentage: 1.0
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: service3
