server:
  port: 8080
spring:
  application:
    name: service1
  sleuth:
    enabled: true
    sampler:
      percentage: 1.0
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: service1
